// Code generated by MockGen. DO NOT EDIT.
// Source: ./ports.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/ZonyxNagi/zonyx-core/internal/core/domain"
	gomock "github.com/golang/mock/gomock"
	status "google.golang.org/genproto/googleapis/rpc/status"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockService) Publish(ctx context.Context, d domain.Directive) (string, *status.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, d)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*status.Status)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Publish indicates an expected call of Publish.
func (mr *MockServiceMockRecorder) Publish(ctx, d interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockService)(nil).Publish), ctx, d)
}

// ReadConfiguration mocks base method.
func (m *MockService) ReadConfiguration(ctx context.Context, send func(domain.Configuration) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadConfiguration", ctx, send)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReadConfiguration indicates an expected call of ReadConfiguration.
func (mr *MockServiceMockRecorder) ReadConfiguration(ctx, send interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadConfiguration", reflect.TypeOf((*MockService)(nil).ReadConfiguration), ctx, send)
}

// Subscribe mocks base method.
func (m *MockService) Subscribe(ctx context.Context, types []domain.EventType, offset *string, send func(domain.Event, string) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, types, offset, send)
	ret0, _ := ret[0].(error)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockServiceMockRecorder) Subscribe(ctx, types, offset, send interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockService)(nil).Subscribe), ctx, types, offset, send)
}

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockProvider) Run(ctx context.Context, emit func(domain.Event) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, emit)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockProviderMockRecorder) Run(ctx, emit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockProvider)(nil).Run), ctx, emit)
}

// Send mocks base method.
func (m *MockProvider) Send(ctx context.Context, d domain.Directive) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, d)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockProviderMockRecorder) Send(ctx, d interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockProvider)(nil).Send), ctx, d)
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Watch mocks base method.
func (m *MockRepository) Watch(ctx context.Context, types []domain.EventType, offset *string, deliver func(domain.Event, string) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", ctx, types, offset, deliver)
	ret0, _ := ret[0].(error)
	return ret0
}

// Watch indicates an expected call of Watch.
func (mr *MockRepositoryMockRecorder) Watch(ctx, types, offset, deliver interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockRepository)(nil).Watch), ctx, types, offset, deliver)
}

// Write mocks base method.
func (m *MockRepository) Write(ctx context.Context, e domain.Event) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", ctx, e)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *MockRepositoryMockRecorder) Write(ctx, e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockRepository)(nil).Write), ctx, e)
}
